name = "ObiterDicta"
uuid = "24410e7c-b831-42e4-8e51-39fbbfdf70b0"
authors = ["Syx Pek and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
